#php7:
# php-fpm -F -y /etc/php-fpm.conf

nginx-proxy:
  #image: dr.yellotravel.com/nginx-proxy:1.9.6
  image: php7
  command: bash -c "nginx;php-fpm -y /etc/php-fpm.conf"
  #command: bash -c "while [ 0 ]; do sleep 1;done"
  volumes:
    - ./config/www.conf:/etc/php-fpm.d/www.conf
    - ./config/nginx.conf:/etc/nginx/nginx.conf
    - ./config:/var/www/html
    - ./logs:/var/log/nginx
    - /etc/localtime:/etc/localtime:ro
    - ./config/vhost.d:/etc/nginx/vhost.d:ro
    - ./config/php.ini:/etc/php.ini:ro
    - ./config/template:/template

  ports:
   - "80:80"
   - "443:443"
   - "9000:9000"

  environment:
   #  VIRTUAL_HOST: carem.test.co, carea.test.co
   #  CERT_NAME: server
    # WWW_NODEJS: "/home/www_nodejs"
    # APP: "jcs_chat_client/bin/www"
    # NODE_PATH: "/usr/local/node/lib/node_modules"
    DEBUG: "*"
    #PATH: "/usr/local/node/bin:$PATH"
